# Copyright (c) 2016-2020 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Patterns for Making Maps
site_url: https://github.com/cartEdu
site_author: Jeff Howarth
site_description: >-
  Cartography patterns

# Repository
repo_name: jeffhowarth/cartEdu
repo_url: https://github.com/jeffhowarth/cartEdu
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2023 Jeff Howarth

# Configuration
theme:
  logo: images/GG0150-icon.png
  favicon: images/GG0150-icon.png
  name: material
  # custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en

  features:
    - navigation.instant
    # - navigation.sections
    - navigation.indexes 
    - navigation.footer 

    # - navigation.expand 
    - content.code.copy
    - toc.integrate  

  palette:
    scheme: white
    primary: white
    accent: orange
  font:
    # text: Libre Baskerville
    text: Helvetica
    # text: Didact Gothic
    code: Roboto Mono

# extra_css:
#   - stylesheets/extra.css

# Plugins
plugins:
  - search
  - minify

# src and site directories
docs_dir: 'src'
site_dir: 'docs'

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jeffhowarth
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jeffgeographer

# Extensions
markdown_extensions:
  - smarty
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: false
      toc_depth: 4
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: pymdownx-inline
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format 
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list

# Page tree
nav:
  - Title page: index.md  
  - Introduction: introduction.md    
  - Overview of patterns: overview.md
  - GENERAL PATTERNS:  
    - ARTIFACT WITH ART: 
      - Creative notebook: general/artifact/creative-notebook.md  
      - Know your audience: general/artifact/know-your-audience.md  
      - Object in the world: general/artifact/object-in-the-world.md  
    - VISUAL ARRANGEMENT:  
      - Invisible grid: general/arrangement/invisible-grid.md  
      - Window on world: general/arrangement/window-on-world.md  
      - Power position: general/arrangement/power-position.md  
      - Visual center: general/arrangement/visual-center.md  
      - Leaky container: general/arrangement/leaky-container.md  
    - VISUAL ARGUMENT: 
      - Simplify the world: general/argument/simplify-the-world.md  
      - Visual hierarchy: general/argument/visual-hierarchy.md  
      - What is the point?: general/argument/what-is-the-point.md
      - Layering layers: general/argument/layering-layers.md  
      - Bigger appears greater: general/argument/bigger-appears-greater.md  
      - Separable part: general/argument/separable-part.md  
      - Simple palette: general/argument/simple-palette.md  
      - Saturation pops: general/argument/saturation-pops.md  
      - Candle-lit canvas: general/argument/candle-lit-canvas.md  
    - GEOGRAPHIC FRAMEWORK:  
      - Topos trumps location: general/framework/topos-trumps-location.md  
      - Where in the world: general/framework/where-in-the-world.md  
      - Scales of thought: general/framework/scales-of-thought.md  
      - Purposeful projection: general/framework/purposeful-projection.md  
      - Scale bar: general/framework/scale-bar.md  
      - Plumb central meridian: general/framework/plumb-central-meridian.md  
      - Which was is up?: general/framework/which-way-is-up.md
      - Graticule graph paper: general/framework/graticule-graph-paper.md  
      - Blue graticule: general/framework/blue-graticule.md  
      - Suggested nieghbor: general/framework/suggested-neighbor.md  
      - Region provides axis: general/framework/region-provides-axis.md  
      - Reinforce reference image: general/framework/reinforce-reference-image.md     
      - Border index: general/framework/border-index.md  
      - Messy metaphor of magnetism: general/framework/messy-metaphor-magnetism.md  
      - Time as distance: general/framework/time-as-distance.md  
    - SCALE:
      - Simplify without distortion: general/scale/simplify-without-distortion.md   
    - COLOR:  
      - Light through the keyhole: general/color/light-through-the-keyhole.md 
      - Stop with the stoplight: general/color/stop-with-the-stoplight.md  
      - Get over the rainbow: general/color/get-over-the-rainbow.md  
    - ICONS:   
      - Symbol resembles referent: general/icons/symbol-resembles-referent.md
      - Linguistic metaphor: general/icons/linguistic-metaphor.md  
      - Legible icons: general/icons/legible-icon.md  
    - LETTERING:  
      - Type taxonomy: general/lettering/type-taxonomy.md  
      - Visual association: general/lettering/visual-association.md  
      - Rights of way: general/lettering/rights-of-way.md  
      - According to Imhof: general/lettering/according-to-Imhof.md  
      - Between but not touching: general/lettering/between-but-not-touching.md 
      - Put labels in place: general/lettering/put-labels-in-place.md   
      - Styles of place and time: general/lettering/styles-of-place-and-time.md  
      - Areal labels: general/lettering/areal-labels.md  
    # - TERRAIN:
    #   - Structure at a glance: general/terrain/structure-at-a-glance.md 
    #   - Right-hand legacy: general/terrain/right-hand-legacy.md   
    #   - Late sunrise: general/terrain/late-sunrise.md   
    #   - Half-tone landscape: general/terrain/half-tone-landscape.md   
    #   - Illuminating oblique: general/terrain/illuminating-oblique.md  
    #   - The steeper, the darker: general/terrain/the-steeper-the-darker.md
    #   - Hypsometric tint: general/terrain/hypsometric-tint.md  
    #   - Skeletal lines: general/terrain/skeletal-lines.md  
    #   - Ripples: general/terrain/ripples.md  
    #   - Hachures: general/terrain/hachures.md  
    #   - Grading lines: general/terrain/grading-lines.md  
    - ISOLINES:  
      - Index contours: general/isolines/index-contours.md  
      - Lines, not fills: general/isolines/lines-not-fills.md
      - Ladder labels: general/isolines/ladder-labels.md  
      - Leveled labels: general/isolines/leveled-labels.md  
    - LEGENDS:  
      - Dictionary definitions: general/legend/dictionary-definitions.md  
      - Tobler meets Sullivan: general/legend/Tobler-meets-Sullivan.md  
      - Define in context: general/legend/define-in-context.md  
  - SPECIFIC PATTERNS:
    - Water: specific/patterns-water.md  
  - GOOD EXAMPLES:  
    - REFERENCE MAPS:
      - Political: examples/reference-political.md  
      - Topographic: examples/reference-topographic.md  


    
  
#  - License: license.md
