# Copyright (c) 2016-2020 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Cart Patterns
site_url: https://github.com/cartEdu
site_author: Jeff Howarth
site_description: >-
  Cartography patterns

# Repository
repo_name: jeffhowarth/cartEdu
repo_url: https://github.com/jeffhowarth/cartEdu
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2023 Jeff Howarth

# Configuration
theme:
  logo: images/GG0150-icon.png
  favicon: images/GG0150-icon.png
  name: material
  # custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en

  features:
    # - tabs
    - navigation.instant
    # - navigation.sections
    - navigation.indexes 
    - navigation.footer 

    - navigation.expand 
    - content.code.copy

  palette:
    scheme: white
    primary: white
    accent: orange
  font:
    text: Libre Baskerville
    # text: Didact Gothic
    code: Roboto Mono

extra_css:
  - extra.css

# Plugins
plugins:
  - search
  - minify

# src and site directories
docs_dir: 'src'
site_dir: 'docs'

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jeffhowarth
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jeffgeographer

# Extensions
markdown_extensions:
  - smarty
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: false
      toc_depth: 4
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: pymdownx-inline
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format 
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list

# Page tree
nav:
  - Welcome: index.md  
  - Overview of patterns: overview.md  
  - MORE ARTIFACT THAN ART: 
    - Know your audience: artifact/know-your-audience.md  
    - Object in the world: artifact/object-in-the-world.md  
    - What is the point?: artifact/what-is-the-point.md
  - VISUAL ARGUMENT: 
    - Simplify the world: argument/simplify-the-world.md  
    - Visual hierarchy: argument/visual-hierarchy.md  
    - Layering layers: argument/layering-layers.md  
    - Bigger appears greater: argument/bigger-appears-greater.md  
    - Separable part: argument/separable-part.md  
    - Simple palette: argument/simple-palette.md  
    - Saturation pops: argument/saturation-pops.md  
    - Candle-lit canvas: argument/candle-lit-canvas.md  
  - VISUAL ARRANGEMENT:  
    - Window on world: arrangement/window-on-world.md  
    - Power position: arrangement/power-position.md  
    - Visual center: arrangement/visual-center.md  
    - Leaky container: arrangement/leaky-container.md  
  - GEOGRAPHIC FRAMEWORK:  
    - Topos trumps location: framework/topos-trumps-location.md  
    - Where in the world: framework/where-in-the-world.md  
    - Scales of thought: framework/scales-of-thought.md  
    - Purposeful projection: framework/purposeful-projection.md  
    - Scale bar: framework/scale-bar.md  
    - Plumb central meridian: framework/plumb-central-meridian.md  
    - Which was is up?: framework/which-way-is-up.md
    - Graticule graph paper: framework/graticule-graph-paper.md  
    - Blue graticule: framework/blue-graticule.md  
    - Suggested nieghbor: framework/suggested-neighbor.md  
    - Region provides axis: framework/region-provides-axis.md  
    - Reinforce reference image: framework/reinforce-reference-image.md     
    - Border index: framework/border-index.md  
    - Messy metaphor of magnetism: framework/messy-metaphor-magnetism.md  
    - Time as distance: framework/time-as-distance.md    
  - SYMBOLS:  
    - Symbol resembles referent: symbol/symbol-resembles-referent.md
    - Linguistic metaphor: symbol/linguistic-metaphor.md  
    - Simplify without distortion: symbol/simplify-without-distortion.md  
    - Part stands for whole: symbol/part-stands-for-whole.md  
    - Legible icons: symbol/legible-icon.md  
    - Light through the keyhole: symbol/light-through-the-keyhole.md 
    - Stop with the stoplight: symbol/stop-with-the-stoplight.md  
    - Get over the rainbow: symbol/get-over-the-rainbow.md  
  - LETTERING:  
    - Type taxonomy: lettering/type-taxonomy.md  
    - Visual association: lettering/visual-association.md  
    - Rights of way: lettering/rights-of-way.md  
    - According to Imhof: lettering/according-to-Imhof.md  
    - Between but not touching: lettering/between-but-not-touching.md 
    - Put labels in place: lettering/put-labels-in-place.md   
    - Styles of place and time: lettering/styles-of-place-and-time.md  
    - Areal labels: lettering/areal-labels.md  
  - TERRAIN:
    - Structure at a glance: terrain/structure-at-a-glance.md 
    - Right-hand legacy: terrain/right-hand-legacy.md   
    - Late sunrise: terrain/late-sunrise.md   
    - Half-tone landscape: terrain/half-tone-landscape.md   
    - Illuminating oblique: terrain/illuminating-oblique.md  
    - Hypsometric tint: terrain/hypsometric-tint.md  
    - Skeletal lines: terrain/skeletal-lines.md  
    - Ripples: terrain/ripples.md  
    - Hachures: terrain/hachures.md  
    - Grading lines: terrain/grading-lines.md  
  - ISOLINES:  
    - Index contours: isolines/index-contours.md  
    - Lines, not fills: isolines/lines-not-fills.md
    - Ladder labels: isolines/ladder-labels.md  
    - Leveled labels: isolines/leveled-labels.md  
  - LEGENDS:  
    - Dictionary definitions: legend/dictionary-definitions.md  
    - Tobler meets Sullivan: legend/Tobler-meets-Sullivan.md  
    - Define in context: legend/define-in-context.md  
  
#  - License: license.md
