# Copyright (c) 2016-2020 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Patterns for Making Maps
site_url: https://github.com/cartEdu
site_author: Jeff Howarth
site_description: >-
  Cartography patterns

# Repository
repo_name: jeffhowarth/cartEdu
repo_url: https://github.com/jeffhowarth/cartEdu
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2023 Jeff Howarth

# Configuration
theme:
  logo: images/GG0150-icon.png
  favicon: images/GG0150-icon.png
  name: material
  # custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en

  features:
    - navigation.instant
    # - navigation.sections
    - navigation.indexes 
    - navigation.footer 

    # - navigation.expand 
    - content.code.copy
    - toc.integrate  

  palette:
    scheme: white
    primary: white
    accent: orange
  font:
    # text: Libre Baskerville
    text: Helvetica
    # text: Didact Gothic
    code: Roboto Mono

# extra_css:
#   - stylesheets/extra.css

# Plugins
plugins:
  - search
  - minify

# src and site directories
docs_dir: 'src'
site_dir: 'docs'

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jeffhowarth
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jeffgeographer

# Extensions
markdown_extensions:
  - smarty
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: false
      toc_depth: 4
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: pymdownx-inline
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format 
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list

# Page tree
nav:
  - Home: index.md  
  - I. General patterns:  
    - Introduction: general/introduction.md   
    - Looking to see: general/looking-to-see.md    
    - Setting your problem: general/problem-setting.md 
    - Compilation: general/compilation.md  
    - Arrangement: general/arrangement.md    
    - Layering: general/layering.md
    - Geographic framework: general/geographic-framework.md   
    - Scale & Detail: general/scale-detail.md  
    - Color: general/color.md   
    - Icons: general/icons.md    
    - Lettering: general/lettering.md    
    - Key: general/key.md   
  - II. Thematic patterns: 
    - Text on maps: thematic/text-on-maps.md     
    - Water: thematic/patterns-water.md  
  - III. Examples:
    - Reference maps:  
      - Political maps: examples/political.md 
      - Road maps: examples/roads.md  
      - Topographic maps: examples/topographic.md  
    - Social themes:    
      - Health maps: examples/health.md  
      - Moral statistics maps: examples/moral-statistics.md
      - Population maps: examples/population.md  
      - Route maps: examples/routes.md  
      - War maps: examples/war.md  
    - Physical themes:
      - Bathymetry: examples/bathymetry.md  
      - Mountains: examples/mountains.md
    - Cartographers:  
      - Richard Edes Harrison (1901-1994): examples/cartographer-harrison.md  
      - Eduard Imhof (1895-1986): examples/cartographer-imhof.md  
      - Tom Patterson: examples/cartographer-patterson.md  
      - Erwin Raisz (1893-1968): examples/cartographer-raisz.md  






    
  
#  - License: license.md
